/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ControleCaixa;
import controle.ControleFuncionario;
import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.Caixa;

/**
 *
 * @author Eduardo Faustino
 */
public class AberturaCaixa extends javax.swing.JDialog {

    /**
     * Creates new form TelaAberturaCaixa
     */
    public AberturaCaixa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        if (ControleCaixa.isCaixaAberto()) {
            pnlAbrir.setEnabled(false);
            pnlAbrir.setBackground(Color.gray);
            pnlFechar.setEnabled(true);
            pnlFechar.setBackground(new Color(153, 0, 0));
        } else {
            pnlFechar.setEnabled(false);
            pnlFechar.setBackground(Color.gray);
            pnlAbrir.setEnabled(true);
            pnlAbrir.setBackground(new Color(0, 102, 102));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlAbrir = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlFechar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Caixa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        pnlAbrir.setBackground(new java.awt.Color(0, 102, 102));
        pnlAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAbrirMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Abrir");

        javax.swing.GroupLayout pnlAbrirLayout = new javax.swing.GroupLayout(pnlAbrir);
        pnlAbrir.setLayout(pnlAbrirLayout);
        pnlAbrirLayout.setHorizontalGroup(
            pnlAbrirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnlAbrirLayout.setVerticalGroup(
            pnlAbrirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        pnlFechar.setBackground(new java.awt.Color(153, 0, 0));
        pnlFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlFecharMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Fechar");

        javax.swing.GroupLayout pnlFecharLayout = new javax.swing.GroupLayout(pnlFechar);
        pnlFechar.setLayout(pnlFecharLayout);
        pnlFecharLayout.setHorizontalGroup(
            pnlFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnlFecharLayout.setVerticalGroup(
            pnlFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pnlAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(pnlFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlAbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAbrirMouseClicked
        if (!ControleCaixa.isCaixaAberto()) {
            try {
                float valor = Float.parseFloat(JOptionPane.showInputDialog(this,
                        "Digite o valor no caixa", "", JOptionPane.OK_CANCEL_OPTION));
                if (valor > 0) {
                    Caixa c = new Caixa();
                    Date data = new Date();
                    c.setDataAbertura(data);
                    c.setHoraAbertura(data);
                    c.setFuncionario(ControleFuncionario.getUsuarioLogado());
                    c.setSituacao('A');
                    c.setValorAbertura(valor);
                    c.setValorEntrada((float) 0);
                    c.setValorFechamento((float) 0);
                    ControleCaixa cc = new ControleCaixa();
                    cc.salvar(c);
                    ControleCaixa.setCaixaAberto(c);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Valor invalido", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(this, "Valor invalido\n" + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_pnlAbrirMouseClicked

    private void pnlFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlFecharMouseClicked
        if (ControleCaixa.isCaixaAberto()) {
            try {
                float valor = Float.parseFloat(JOptionPane.showInputDialog(this,
                        "Digite o valor no caixa", "", JOptionPane.OK_CANCEL_OPTION));
                if (valor > 0) {
                    Caixa c = ControleCaixa.getCaixaAberto();
                    Date data = new Date();
                    c.setDataFechamento(data);
                    c.setHoraFechamento(data);
                    c.setSituacao('F');
                    c.setValorFechamento(valor);
//                    float valorEntrada = 0;
//                    float valorSaida = 0;
//                    for (Recebimento r : c.getListaRecebimentos()) {
//                        valorEntrada += r.getValor();
//                    }
//                    for (Despesa d : c.getListaDespesas()) {
//                        valorSaida += d.getValor();
//                    }
//                    for (Compra co : c.getListaCompras()) {
//                        valorSaida += co.getValorTotal();
//                    }
//                    c.setValorEntrada(valorEntrada);
//                    c.setValorSaida(valorSaida);
                    ControleCaixa cc = new ControleCaixa();
                    cc.alterar(c);
                    ControleCaixa.setCaixaAberto(null);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Valor invalido", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Valor invalido\n" + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_pnlFecharMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AberturaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AberturaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AberturaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AberturaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AberturaCaixa dialog = new AberturaCaixa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlAbrir;
    private javax.swing.JPanel pnlFechar;
    // End of variables declaration//GEN-END:variables
}
